services:
  postgres:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mse_radar
      POSTGRES_PASSWORD: mse_radar
      POSTGRES_DB: mse_radar
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
